CREATE TABLE WEATHER (   ID SERIAL PRIMARY KEY ,
                         DATA TIMESTAMP,
                         TEMPERATURE  NUMERIC NOT NULL,
                         HUMIDITY NUMERIC );
SELECT * FROM WEATHER;
insert into WEATHER (DATA, HUMIDITY, TEMPERATURE) values ('12.01.2023', 0, 0);

INSERT into WEATHER (ID, DATA, TEMPERATURE, HUMIDITY) VALUES (1, '12.01.2023', 0, 0);


SELECT MAX(ID) FROM WEATHER
SELECT MAX(w.ID) FROM WEATHER w

DROP TABLE WEATHER;
